import type { ResolvedItinerary } from '../../types'

// Generated by scripts/reseed-tokyo-demo.js - do not hand-edit. Re-run that
// script instead, so the demo stays a real output of the current pipeline
// rather than a snapshot that silently drifts away from it.
//
// Photos are local files under /public/demo/tokyo, not Google photo
// references: a reference expires and takes the whole demo card down with it.
export const TOKYO_2_DAYS: ResolvedItinerary = {
  "packed": {
    "label": "Packed & Varied",
    "tagline": "Four neighborhoods, five interests, nonstop discovery.",
    "divergenceLabel": "This itinerary splits interests across two distinct days and neighborhoods, pacing 4–5 activities per day with no stop exceeding two hours, so you experience temples, anime culture, modern architecture, and nightlife as separate chapters rather than a generic mix.",
    "days": [
      {
        "day": 1,
        "theme": "Temples, Modern Tokyo & Nightlife",
        "breakfastAtAccommodation": true,
        "breakfastTime": "09:00",
        "items": [
          {
            "type": "accommodation",
            "name": "ONE@Tokyo by insomnia",
            "categoryTag": "Hotel · Oshiage",
            "address": "1-chōme-19-3 Oshiage, Sumida City, Tokyo 131-0045, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/01-one-tokyo-by-insomnia.jpg",
            "location": {
              "lat": 35.711788899999995,
              "lng": 139.81597779999998
            },
            "hasHours": false,
            "weekdayDescriptions": null,
            "mealType": "breakfast",
            "durationMinutes": 60,
            "travelToNext": "15 minute drive",
            "startTime": "09:00",
            "description": "Breakfast at ONE@Tokyo by insomnia."
          },
          {
            "time": "morning",
            "type": "activity",
            "name": "Sensō-ji",
            "categoryTag": "Landmark · Asakusa",
            "description": "Tokyo's oldest and most famous Buddhist temple, a sprawling complex in historic Asakusa with its iconic Thunder Gate and vibrant traditional atmosphere.",
            "startTime": "10:15",
            "durationMinutes": 75,
            "mealType": null,
            "address": "2-chōme-3-1 Asakusa, Taito City, Tokyo 111-0032, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/02-senso-ji.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.7147651,
              "lng": 139.7966553
            },
            "travelToNext": "25 minute drive"
          },
          {
            "time": "afternoon",
            "type": "activity",
            "name": "Tokyo Midtown",
            "categoryTag": "Shopping · Akasaka",
            "description": "Landmark mixed-use development in Roppongi showcasing contemporary Japanese architecture, design galleries and high-rise views of the city skyline.",
            "startTime": "11:55",
            "durationMinutes": 75,
            "mealType": null,
            "address": "9-chōme-7-1 Akasaka, Minato City, Tokyo 107-0052, Japan",
            "photoUrl": "/demo/tokyo/03-tokyo-midtown.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.6659803,
              "lng": 139.7308747
            },
            "travelToNext": "20 minute drive"
          },
          {
            "time": "lunch",
            "type": "meal",
            "name": "Gonpachi Nishi-Azabu",
            "categoryTag": "Restaurant",
            "description": "Izakaya institution in a renovated warehouse, celebrated for yakitori, small plates and atmospheric group dining perfect for two.",
            "startTime": "13:30",
            "durationMinutes": 60,
            "mealType": "lunch",
            "address": "1-chōme-13-11 Nishiazabu, Minato City, Tokyo 106-0031, Japan",
            "photoUrl": "/demo/tokyo/04-gonpachi-nishi-azabu.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.6601742,
              "lng": 139.7235797
            },
            "travelToNext": "15 minute drive"
          },
          {
            "time": "afternoon",
            "type": "activity",
            "name": "Roppongi Hills",
            "categoryTag": "Architecture · Modern",
            "description": "Iconic urban complex blending offices, retail and residential towers with a rooftop garden offering panoramic views over central Tokyo.",
            "startTime": "14:45",
            "durationMinutes": 150,
            "mealType": null,
            "address": "6-chōme-10-1 Roppongi, Minato City, Tokyo 106-6108, Japan",
            "photoUrl": "/demo/tokyo/05-roppongi-hills.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.6607397,
              "lng": 139.7292319
            },
            "travelToNext": "15 minute drive"
          },
          {
            "time": "morning",
            "type": "activity",
            "name": "Yoyogi Park",
            "categoryTag": "Park · Yoyogikamizonochō",
            "description": "Expansive green space and cultural landmark adjacent to Meiji Shrine, offering walking paths, open-air views and a sense of Tokyo's quieter side.",
            "startTime": "17:30",
            "durationMinutes": 135,
            "mealType": null,
            "address": "2-1 Yoyogikamizonochō, Shibuya, Tokyo 151-0052, Japan",
            "photoUrl": "/demo/tokyo/06-yoyogi-park.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.6700649,
              "lng": 139.6949656
            },
            "travelToNext": "15 minute drive"
          },
          {
            "time": "dinner",
            "type": "meal",
            "name": "MO-MO-PARADISE Shinjuku-Sanchome",
            "categoryTag": "Restaurant · Shinjuku",
            "description": "An all-you-can-eat hot pot restaurant in Shinjuku offering Japanese shabu-shabu and sukiyaki with a lively, casual dining experience.",
            "startTime": "20:00",
            "durationMinutes": 60,
            "mealType": "dinner",
            "address": "Japan, 〒160-0022 Tokyo, Shinjuku City, Shinjuku, 3-chōme−30−１１ 高野第二ビル 8F",
            "photoUrl": "/demo/tokyo/07-mo-mo-paradise-shinjuku-sanchome.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.6911491,
              "lng": 139.7036139
            },
            "travelToNext": "15 minute drive"
          },
          {
            "time": "evening",
            "type": "nightlife",
            "name": "Rokusan Angel (Burlesque Tokyo)",
            "categoryTag": "Nightlife · Roppongi",
            "description": "A burlesque and cabaret nightclub in Roppongi featuring theatrical performances with an international flair in Tokyo's entertainment district.",
            "startTime": "21:15",
            "durationMinutes": 90,
            "mealType": null,
            "address": "Japan, 〒106-0032 Tokyo, Minato City, Roppongi, 3-chōme−8−１５ 日拓ビル B2F",
            "rating": 5,
            "ratingCount": 22320,
            "photoUrl": "/demo/tokyo/08-rokusan-angel-burlesque-tokyo.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: 6:00 PM – 1:00 AM",
              "Tuesday: 6:00 PM – 1:00 AM",
              "Wednesday: 6:00 PM – 1:00 AM",
              "Thursday: 6:00 PM – 1:00 AM",
              "Friday: 6:00 PM – 1:00 AM",
              "Saturday: 6:00 PM – 1:00 AM",
              "Sunday: 6:00 PM – 1:00 AM"
            ],
            "location": {
              "lat": 35.6633285,
              "lng": 139.7341877
            },
            "travelToNext": "25 minute drive"
          },
          {
            "type": "accommodation",
            "name": "ONE@Tokyo by insomnia",
            "categoryTag": "Hotel · Oshiage",
            "address": "1-chōme-19-3 Oshiage, Sumida City, Tokyo 131-0045, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/01-one-tokyo-by-insomnia.jpg",
            "location": {
              "lat": 35.711788899999995,
              "lng": 139.81597779999998
            },
            "hasHours": false,
            "weekdayDescriptions": null,
            "mealType": null,
            "durationMinutes": null,
            "travelToNext": null,
            "startTime": "23:10",
            "description": "Back at ONE@Tokyo by insomnia."
          }
        ],
        "stopCount": 8,
        "pacingLevel": 1
      },
      {
        "day": 2,
        "theme": "Anime Culture & Pop Culture",
        "breakfastAtAccommodation": false,
        "items": [
          {
            "type": "accommodation",
            "name": "ONE@Tokyo by insomnia",
            "categoryTag": "Hotel · Oshiage",
            "address": "1-chōme-19-3 Oshiage, Sumida City, Tokyo 131-0045, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/01-one-tokyo-by-insomnia.jpg",
            "location": {
              "lat": 35.711788899999995,
              "lng": 139.81597779999998
            },
            "hasHours": false,
            "weekdayDescriptions": null,
            "mealType": null,
            "durationMinutes": null,
            "travelToNext": "10 minute drive",
            "startTime": "08:50",
            "description": "Leave ONE@Tokyo by insomnia for breakfast."
          },
          {
            "time": "breakfast",
            "type": "meal",
            "name": "February Cafe",
            "categoryTag": "Café · Komagata",
            "description": "A cafe and coffee shop in the Komagata neighbourhood serving breakfast and refreshments near the Sumida River area.",
            "startTime": "09:00",
            "durationMinutes": 60,
            "mealType": "breakfast",
            "address": "1-chōme-9-8 Komagata, Taito City, Tokyo 111-0043, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/09-february-cafe.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: 8:15 AM – 4:30 PM",
              "Tuesday: 8:15 AM – 4:30 PM",
              "Wednesday: 8:15 AM – 4:30 PM",
              "Thursday: 8:15 AM – 4:30 PM",
              "Friday: 8:15 AM – 4:30 PM",
              "Saturday: 8:15 AM – 5:00 PM",
              "Sunday: 8:15 AM – 5:00 PM"
            ],
            "location": {
              "lat": 35.7083042,
              "lng": 139.7946526
            },
            "travelToNext": "30 minute drive"
          },
          {
            "time": "morning",
            "type": "activity",
            "name": "Takeshita Street",
            "categoryTag": "Landmark",
            "description": "Harajuku's legendary pedestrian alley packed with anime merchandise, costume shops, character boutiques and youth culture storefronts—the heart of Tokyo's pop culture retail.",
            "startTime": "10:30",
            "durationMinutes": 75,
            "mealType": null,
            "address": "1-chōme-16-6 Jingūmae, Shibuya, Tokyo 150-0001, Japan",
            "photoUrl": "/demo/tokyo/10-takeshita-street.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.6712601,
              "lng": 139.7046761
            },
            "travelToNext": "20 minute drive"
          },
          {
            "time": "morning",
            "type": "activity",
            "name": "Kamadera East Heritage",
            "categoryTag": "Landmark · Hōnan",
            "description": "A historical landmark in the Hōnan neighbourhood preserving heritage architecture and local history from the area's past.",
            "startTime": "12:05",
            "durationMinutes": 75,
            "mealType": null,
            "address": "2-chōme-6-11 Hōnan, Suginami City, Tokyo 168-0062, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/11-kamadera-east-heritage.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: Open 24 hours",
              "Tuesday: Open 24 hours",
              "Wednesday: Open 24 hours",
              "Thursday: Open 24 hours",
              "Friday: Open 24 hours",
              "Saturday: Open 24 hours",
              "Sunday: Open 24 hours"
            ],
            "location": {
              "lat": 35.6809474,
              "lng": 139.65859989999998
            },
            "travelToNext": "10 minute drive"
          },
          {
            "type": "meal",
            "name": "Senrigan",
            "categoryTag": "Restaurant · Komaba",
            "description": "A ramen restaurant in the Komaba neighbourhood serving Japanese noodle dishes in a local setting near university areas.",
            "startTime": "13:30",
            "durationMinutes": 60,
            "mealType": "lunch",
            "travelToNext": "15 minute drive",
            "photoUrl": "/demo/tokyo/12-senrigan.jpg",
            "location": {
              "lat": 35.6640124,
              "lng": 139.6784917
            },
            "address": "4-chōme-6-8 Komaba, Meguro City, Tokyo 153-0041, Japan",
            "rating": null,
            "ratingCount": null,
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: 11:00 AM – 3:00 PM, 5:00 – 9:00 PM",
              "Tuesday: 11:00 AM – 3:00 PM, 5:00 – 9:00 PM",
              "Wednesday: Closed",
              "Thursday: 11:00 AM – 3:00 PM, 5:00 – 9:00 PM",
              "Friday: 11:00 AM – 3:00 PM, 5:00 – 9:00 PM",
              "Saturday: 11:00 AM – 3:00 PM, 5:00 – 9:00 PM",
              "Sunday: 11:00 AM – 3:00 PM, 5:00 – 9:00 PM"
            ]
          },
          {
            "time": "afternoon",
            "type": "activity",
            "name": "Shinjuku Gyoen National Garden",
            "categoryTag": "Garden · Naitōmachi",
            "description": "Historic 144-acre garden in central Shinjuku blending Japanese, French and English landscapes, offering a serene contrast to the city's urban energy.",
            "startTime": "14:45",
            "durationMinutes": 135,
            "mealType": null,
            "address": "11 Naitōmachi, Shinjuku City, Tokyo 160-0014, Japan",
            "rating": 4.6,
            "ratingCount": 45637,
            "photoUrl": "/demo/tokyo/13-shinjuku-gyoen-national-garden.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: Closed",
              "Tuesday: 9:00 AM – 6:00 PM",
              "Wednesday: 9:00 AM – 6:00 PM",
              "Thursday: 9:00 AM – 6:00 PM",
              "Friday: 9:00 AM – 6:00 PM",
              "Saturday: 9:00 AM – 6:00 PM",
              "Sunday: 9:00 AM – 6:00 PM"
            ],
            "location": {
              "lat": 35.685176299999995,
              "lng": 139.7100517
            },
            "travelToNext": "25 minute drive"
          },
          {
            "type": "activity",
            "name": "Meiji Jingu",
            "address": "1-1 Yoyogikamizonochō, Shibuya, Tokyo 151-8557, Japan",
            "location": {
              "lat": 35.6763976,
              "lng": 139.6993259
            },
            "description": "Landmark in Yoyogikamizonochō.",
            "adoptedFrom": {
              "neighbourhood": "Yoyogikamizonochō",
              "types": [
                "shinto_shrine",
                "tourist_attraction",
                "place_of_worship",
                "association_or_organization",
                "point_of_interest",
                "establishment"
              ]
            },
            "categoryTag": "Landmark · Yoyogikamizonochō",
            "startTime": "17:25",
            "durationMinutes": 135,
            "mealType": null,
            "travelToNext": "20 minute drive",
            "photoUrl": "/demo/tokyo/14-meiji-jingu.jpg",
            "rating": null,
            "ratingCount": null,
            "hasHours": false,
            "weekdayDescriptions": null
          },
          {
            "time": "dinner",
            "type": "meal",
            "name": "Sukiyabashi Jiro Roppongi Hills Restaurant",
            "categoryTag": "Restaurant",
            "description": "Celebrated sushi restaurant honoring Tokyo's culinary tradition with pristine seasonal fish, precise technique and an intimate omakase counter experience.",
            "startTime": "20:00",
            "durationMinutes": 60,
            "mealType": "dinner",
            "address": "Japan, 〒106-0032 Tokyo, Minato City, Roppongi, 6-chōme−12−２ 六本木けやき坂通り 3F",
            "photoUrl": "/demo/tokyo/15-sukiyabashi-jiro-roppongi-hills-restaura.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.6586978,
              "lng": 139.72914459999998
            },
            "travelToNext": "30 minute drive"
          },
          {
            "type": "accommodation",
            "name": "ONE@Tokyo by insomnia",
            "categoryTag": "Hotel · Oshiage",
            "address": "1-chōme-19-3 Oshiage, Sumida City, Tokyo 131-0045, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/01-one-tokyo-by-insomnia.jpg",
            "location": {
              "lat": 35.711788899999995,
              "lng": 139.81597779999998
            },
            "hasHours": false,
            "weekdayDescriptions": null,
            "mealType": null,
            "durationMinutes": null,
            "travelToNext": null,
            "startTime": "21:30",
            "description": "Back at ONE@Tokyo by insomnia."
          }
        ],
        "stopCount": 8,
        "pacingLevel": 1
      }
    ],
    "pacingLabel": "Busy"
  },
  "slow": {
    "label": "Slow & Immersive",
    "tagline": "Deep dives into Tokyo's soul, fewer stops, more time.",
    "divergenceLabel": "This plan trades activity count for unhurried immersion, spending 90+ minutes at each major stop rather than rushing through multiple sights per day.",
    "days": [
      {
        "day": 1,
        "theme": "Sacred Temples & Modern Architecture",
        "breakfastAtAccommodation": true,
        "breakfastTime": "09:00",
        "items": [
          {
            "type": "accommodation",
            "name": "ONE@Tokyo by insomnia",
            "categoryTag": "Hotel · Oshiage",
            "address": "1-chōme-19-3 Oshiage, Sumida City, Tokyo 131-0045, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/01-one-tokyo-by-insomnia.jpg",
            "location": {
              "lat": 35.711788899999995,
              "lng": 139.81597779999998
            },
            "hasHours": false,
            "weekdayDescriptions": null,
            "mealType": "breakfast",
            "durationMinutes": 120,
            "travelToNext": "30 minute drive",
            "startTime": "09:00",
            "description": "Breakfast at ONE@Tokyo by insomnia."
          },
          {
            "time": "afternoon",
            "type": "activity",
            "name": "Roppongi Hills Mori Tower",
            "categoryTag": "Shopping",
            "description": "An iconic skyscraper offering panoramic views of Tokyo's skyline and architectural landscape from its observation deck.",
            "startTime": "11:30",
            "durationMinutes": 105,
            "mealType": null,
            "address": "6-chōme-10-1 Roppongi, Minato City, Tokyo 106-0032, Japan",
            "photoUrl": "/demo/tokyo/16-roppongi-hills-mori-tower.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.6607345,
              "lng": 139.7292066
            },
            "travelToNext": "15 minute drive"
          },
          {
            "time": "lunch",
            "type": "meal",
            "name": "Gonpachi Nishi-Azabu",
            "categoryTag": "Restaurant",
            "description": "A stylish izakaya in Minato known for creative Japanese cuisine and atmospheric design, ideal for a relaxed midday meal.",
            "startTime": "13:30",
            "durationMinutes": 120,
            "mealType": "lunch",
            "address": "1-chōme-13-11 Nishiazabu, Minato City, Tokyo 106-0031, Japan",
            "photoUrl": "/demo/tokyo/04-gonpachi-nishi-azabu.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.6601742,
              "lng": 139.7235797
            },
            "travelToNext": "15 minute drive"
          },
          {
            "time": "morning",
            "type": "activity",
            "name": "Yoyogi Park",
            "categoryTag": "Park · Yoyogikamizonochō",
            "description": "A sprawling urban forest and cultural landmark adjacent to Meiji Shrine, perfect for a leisurely walk and soaking in Tokyo's green spaces.",
            "startTime": "15:45",
            "durationMinutes": 105,
            "mealType": null,
            "address": "2-1 Yoyogikamizonochō, Shibuya, Tokyo 151-0052, Japan",
            "photoUrl": "/demo/tokyo/06-yoyogi-park.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.6700649,
              "lng": 139.6949656
            },
            "travelToNext": "25 minute drive"
          },
          {
            "time": "morning",
            "type": "activity",
            "name": "Meiji Jingu",
            "categoryTag": "Landmark · Yoyogikamizonochō",
            "description": "A serene Shinto shrine set in a forested park in central Tokyo, offering a peaceful escape and traditional architecture.",
            "startTime": "17:55",
            "durationMinutes": 105,
            "mealType": null,
            "address": "1-1 Yoyogikamizonochō, Shibuya, Tokyo 151-8557, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/17-meiji-jingu.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.6763976,
              "lng": 139.6993259
            },
            "travelToNext": "20 minute drive"
          },
          {
            "time": "dinner",
            "type": "meal",
            "name": "MO-MO-PARADISE Shinjuku-Sanchome",
            "categoryTag": "Restaurant · Shinjuku",
            "description": "A hot pot restaurant in Shinjuku serving Japanese-style shabu-shabu and sukiyaki with all-you-can-eat options.",
            "startTime": "20:00",
            "durationMinutes": 120,
            "mealType": "dinner",
            "address": "Japan, 〒160-0022 Tokyo, Shinjuku City, Shinjuku, 3-chōme−30−１１ 高野第二ビル 8F",
            "photoUrl": "/demo/tokyo/07-mo-mo-paradise-shinjuku-sanchome.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.6911491,
              "lng": 139.7036139
            },
            "travelToNext": "20 minute drive"
          },
          {
            "time": "evening",
            "type": "activity",
            "name": "CROSS ROPPONGI",
            "categoryTag": "Nightlife · Roppongi",
            "description": "A nightclub and bar in Roppongi, part of Tokyo's lively entertainment district known for its nightlife scene.",
            "startTime": "22:20",
            "durationMinutes": 90,
            "mealType": null,
            "address": "Japan, 〒106-0032 Tokyo, Minato City, Roppongi, 6-chōme−1−３ 六門ビル 3F",
            "rating": 4.8,
            "ratingCount": 413,
            "photoUrl": "/demo/tokyo/18-cross-roppongi.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: Closed",
              "Tuesday: 8:00 PM – 5:00 AM",
              "Wednesday: 8:00 PM – 5:00 AM",
              "Thursday: 8:00 PM – 5:00 AM",
              "Friday: 8:00 PM – 5:00 AM",
              "Saturday: 8:00 PM – 5:00 AM",
              "Sunday: Closed"
            ],
            "location": {
              "lat": 35.6628024,
              "lng": 139.7322523
            },
            "travelToNext": "25 minute drive"
          },
          {
            "type": "accommodation",
            "name": "ONE@Tokyo by insomnia",
            "categoryTag": "Hotel · Oshiage",
            "address": "1-chōme-19-3 Oshiage, Sumida City, Tokyo 131-0045, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/01-one-tokyo-by-insomnia.jpg",
            "location": {
              "lat": 35.711788899999995,
              "lng": 139.81597779999998
            },
            "hasHours": false,
            "weekdayDescriptions": null,
            "mealType": null,
            "durationMinutes": null,
            "travelToNext": null,
            "startTime": "00:15",
            "description": "Back at ONE@Tokyo by insomnia."
          }
        ],
        "stopCount": 7,
        "pacingLevel": 0.88
      },
      {
        "day": 2,
        "theme": "Anime & Pop Culture",
        "breakfastAtAccommodation": false,
        "items": [
          {
            "type": "accommodation",
            "name": "ONE@Tokyo by insomnia",
            "categoryTag": "Hotel · Oshiage",
            "address": "1-chōme-19-3 Oshiage, Sumida City, Tokyo 131-0045, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/01-one-tokyo-by-insomnia.jpg",
            "location": {
              "lat": 35.711788899999995,
              "lng": 139.81597779999998
            },
            "hasHours": false,
            "weekdayDescriptions": null,
            "mealType": null,
            "durationMinutes": null,
            "travelToNext": "25 minute drive",
            "startTime": "08:35",
            "description": "Leave ONE@Tokyo by insomnia for breakfast."
          },
          {
            "time": "breakfast",
            "type": "meal",
            "name": "Cafe la Voie",
            "categoryTag": "Café · Nishishinjuku",
            "description": "A cafe and coffee shop in Nishishinjuku offering breakfast and light meals in a convenient location.",
            "startTime": "09:00",
            "durationMinutes": 120,
            "mealType": "breakfast",
            "address": "Japan, 〒160-0023 Tokyo, Shinjuku City, Nishishinjuku, 1-chōme−23−１ 1F",
            "rating": 3.5,
            "ratingCount": 501,
            "photoUrl": "/demo/tokyo/19-cafe-la-voie.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: 7:00 AM – 10:00 PM",
              "Tuesday: 7:00 AM – 10:00 PM",
              "Wednesday: 7:00 AM – 10:00 PM",
              "Thursday: 7:00 AM – 10:00 PM",
              "Friday: 7:00 AM – 10:00 PM",
              "Saturday: 7:00 AM – 10:00 PM",
              "Sunday: 7:00 AM – 10:00 PM"
            ],
            "location": {
              "lat": 35.6897382,
              "lng": 139.6961738
            },
            "travelToNext": "15 minute drive"
          },
          {
            "time": "morning",
            "type": "activity",
            "name": "Kamadera East Heritage",
            "categoryTag": "Landmark · Hōnan",
            "description": "A historical landmark in the Hōnan neighbourhood, designated as a heritage site of cultural significance.",
            "startTime": "11:15",
            "durationMinutes": 120,
            "mealType": null,
            "address": "2-chōme-6-11 Hōnan, Suginami City, Tokyo 168-0062, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/20-kamadera-east-heritage.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: Open 24 hours",
              "Tuesday: Open 24 hours",
              "Wednesday: Open 24 hours",
              "Thursday: Open 24 hours",
              "Friday: Open 24 hours",
              "Saturday: Open 24 hours",
              "Sunday: Open 24 hours"
            ],
            "location": {
              "lat": 35.6809474,
              "lng": 139.65859989999998
            },
            "travelToNext": "15 minute drive"
          },
          {
            "time": "lunch",
            "type": "meal",
            "name": "Senrigan",
            "categoryTag": "Restaurant · Komaba",
            "description": "A ramen restaurant in Komaba serving traditional Japanese noodle dishes in a local neighbourhood setting.",
            "startTime": "13:30",
            "durationMinutes": 120,
            "mealType": "lunch",
            "address": "4-chōme-6-8 Komaba, Meguro City, Tokyo 153-0041, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/21-senrigan.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: 11:00 AM – 3:00 PM, 5:00 – 9:00 PM",
              "Tuesday: 11:00 AM – 3:00 PM, 5:00 – 9:00 PM",
              "Wednesday: Closed",
              "Thursday: 11:00 AM – 3:00 PM, 5:00 – 9:00 PM",
              "Friday: 11:00 AM – 3:00 PM, 5:00 – 9:00 PM",
              "Saturday: 11:00 AM – 3:00 PM, 5:00 – 9:00 PM",
              "Sunday: 11:00 AM – 3:00 PM, 5:00 – 9:00 PM"
            ],
            "location": {
              "lat": 35.6640124,
              "lng": 139.6784917
            },
            "travelToNext": "15 minute drive"
          },
          {
            "time": "morning",
            "type": "activity",
            "name": "Takeshita Street",
            "categoryTag": "Landmark",
            "description": "Tokyo's most iconic youth fashion and pop-culture destination, packed with anime shops, character merchandise, and kawaii fashion boutiques.",
            "startTime": "15:45",
            "durationMinutes": 105,
            "mealType": null,
            "address": "1-chōme-16-6 Jingūmae, Shibuya, Tokyo 150-0001, Japan",
            "photoUrl": "/demo/tokyo/10-takeshita-street.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.6712601,
              "lng": 139.7046761
            },
            "travelToNext": "30 minute drive"
          },
          {
            "time": "afternoon",
            "type": "activity",
            "name": "Akihabara Electric Town",
            "categoryTag": "Landmark",
            "description": "Tokyo's electronics and anime mecca, filled with multi-story shops selling manga, anime, games, and rare collectibles.",
            "startTime": "18:00",
            "durationMinutes": 105,
            "mealType": null,
            "address": "1 Chome-12 Sotokanda, Chiyoda City, Tokyo 101-0021, Japan",
            "photoUrl": "/demo/tokyo/22-akihabara-electric-town.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.699717799999995,
              "lng": 139.7713799
            },
            "travelToNext": "15 minute drive"
          },
          {
            "type": "meal",
            "name": "Tsukishima Monja Okoge Asakusa",
            "categoryTag": "Restaurant · Asakusa",
            "description": "A Japanese restaurant in Asakusa specializing in monjayaki, a savory pan-fried batter dish popular in Tokyo.",
            "startTime": "20:00",
            "durationMinutes": 120,
            "mealType": "dinner",
            "travelToNext": "10 minute drive",
            "photoUrl": "/demo/tokyo/23-tsukishima-monja-okoge-asakusa.jpg",
            "location": {
              "lat": 35.7125187,
              "lng": 139.7972586
            },
            "address": "Japan, 〒111-0032 Tokyo, Taito City, Asakusa, 1-chōme−35−９ ザグローヴ",
            "rating": null,
            "ratingCount": null,
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: 10:45 AM – 11:00 PM",
              "Tuesday: 10:45 AM – 11:00 PM",
              "Wednesday: 10:45 AM – 11:00 PM",
              "Thursday: 10:45 AM – 11:00 PM",
              "Friday: 10:45 AM – 11:00 PM",
              "Saturday: 10:30 AM – 11:00 PM",
              "Sunday: 10:30 AM – 11:00 PM"
            ]
          },
          {
            "type": "accommodation",
            "name": "ONE@Tokyo by insomnia",
            "categoryTag": "Hotel · Oshiage",
            "address": "1-chōme-19-3 Oshiage, Sumida City, Tokyo 131-0045, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/01-one-tokyo-by-insomnia.jpg",
            "location": {
              "lat": 35.711788899999995,
              "lng": 139.81597779999998
            },
            "hasHours": false,
            "weekdayDescriptions": null,
            "mealType": null,
            "durationMinutes": null,
            "travelToNext": null,
            "startTime": "22:10",
            "description": "Back at ONE@Tokyo by insomnia."
          }
        ],
        "stopCount": 7,
        "pacingLevel": 0.88
      }
    ],
    "pacingLabel": "Relaxed"
  }
}

// The accommodation the demo was generated against. demoTrips.js imports this
// rather than keeping its own copy, so the card, the Finalise screen and the
// itinerary's bookend stops can never disagree about which hotel this is.
export const TOKYO_ACCOMMODATION = {
  "placeId": "ChIJ718ioimPGGARcwFhGRknToY",
  "name": "ONE@Tokyo by insomnia",
  "categoryTag": "Hotel · Oshiage",
  "address": "1-chōme-19-3 Oshiage, Sumida City, Tokyo 131-0045, Japan",
  "priceLevelLabel": null,
  "photoUrl": "/demo/tokyo/01-one-tokyo-by-insomnia.jpg",
  "location": {
    "lat": 35.711788899999995,
    "lng": 139.81597779999998
  },
  "budget": "Standard",
  "nights": 2,
  "priceRange": {
    "min": 15000,
    "max": 80000,
    "currencyCode": "JPY",
    "estimated": true
  },
  "destinationCurrency": "JPY"
}
