import type { ResolvedItinerary } from '../../types'

// Generated by scripts/reseed-tokyo-demo.js - do not hand-edit. Re-run that
// script instead, so the demo stays a real output of the current pipeline
// rather than a snapshot that silently drifts away from it.
//
// Photos are local files under /public/demo/tokyo, not Google photo
// references: a reference expires and takes the whole demo card down with it.
export const TOKYO_2_DAYS: ResolvedItinerary = {
  "packed": {
    "label": "Packed & Varied",
    "tagline": "Four neighbourhoods, five sights per day, constant motion",
    "divergenceLabel": "This plan stacks 4-5 activities into each day with short stops across multiple districts, prioritizing breadth and variety over depth at any single location.",
    "days": [
      {
        "day": 1,
        "theme": "Anime Culture & Modern Temples",
        "breakfastAtAccommodation": false,
        "items": [
          {
            "type": "accommodation",
            "name": "Mandarin Oriental, Tokyo",
            "categoryTag": "Hotel · Nihonbashimuromachi",
            "address": "2-chōme-1-1 Nihonbashimuromachi, Chuo City, Tokyo 103-8328, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/01-mandarin-oriental-tokyo.jpg",
            "location": {
              "lat": 35.6870475,
              "lng": 139.7730634
            },
            "hasHours": false,
            "weekdayDescriptions": null,
            "mealType": null,
            "durationMinutes": null,
            "travelToNext": "10 minute drive",
            "startTime": "08:50",
            "description": "Leave Mandarin Oriental, Tokyo for breakfast."
          },
          {
            "time": "breakfast",
            "type": "meal",
            "name": "Marutake",
            "categoryTag": "Shop · Tsukiji",
            "description": "A deli and food store in Tsukiji where visitors can pick up fresh breakfast items and local specialties from the market area.",
            "startTime": "09:00",
            "durationMinutes": 60,
            "mealType": "breakfast",
            "address": "4-chōme-10-10 Tsukiji, Chuo City, Tokyo 104-0045, Japan",
            "rating": 4.1,
            "ratingCount": 1457,
            "priceLevel": "PRICE_LEVEL_INEXPENSIVE",
            "photoUrl": "/demo/tokyo/02-marutake.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: 4:30 AM – 2:00 PM",
              "Tuesday: 4:30 AM – 2:00 PM",
              "Wednesday: 8:00 AM – 2:00 PM",
              "Thursday: 4:30 AM – 2:00 PM",
              "Friday: 4:30 AM – 2:00 PM",
              "Saturday: 4:30 AM – 2:00 PM",
              "Sunday: 8:00 AM – 2:00 PM"
            ],
            "location": {
              "lat": 35.6651719,
              "lng": 139.7700056
            },
            "travelToNext": "20 minute drive"
          },
          {
            "time": "afternoon",
            "type": "activity",
            "name": "Roppongi Hills Mori Tower",
            "categoryTag": "Shopping · Roppongi",
            "description": "A landmark mixed-use tower exemplifying Tokyo's modern urban architecture, with a sky observatory offering sweeping city views from the 52nd floor.",
            "startTime": "10:20",
            "durationMinutes": 165,
            "mealType": null,
            "address": "6-chōme-10-1 Roppongi, Minato City, Tokyo 106-0032, Japan",
            "rating": 4.3,
            "ratingCount": 4426,
            "priceLevel": null,
            "photoUrl": "/demo/tokyo/03-roppongi-hills-mori-tower.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: 11:00 AM – 11:00 PM",
              "Tuesday: 11:00 AM – 11:00 PM",
              "Wednesday: 11:00 AM – 11:00 PM",
              "Thursday: 11:00 AM – 11:00 PM",
              "Friday: 11:00 AM – 11:00 PM",
              "Saturday: 11:00 AM – 11:00 PM",
              "Sunday: 11:00 AM – 11:00 PM"
            ],
            "location": {
              "lat": 35.6607345,
              "lng": 139.7292066
            },
            "travelToNext": "25 minute drive"
          },
          {
            "time": "lunch",
            "type": "meal",
            "name": "ICHIRAN Shinjuku Station Central East Exit",
            "categoryTag": "Restaurant · Shinjuku",
            "description": "A ramen restaurant near Shinjuku Station known for its individual booth seating and rich tonkotsu broth that you can customize to taste.",
            "startTime": "13:30",
            "durationMinutes": 60,
            "mealType": "lunch",
            "address": "Japan, 〒160-0022 Tokyo, Shinjuku City, Shinjuku, 3-chōme−34−１１ Peace Bldg., B1F",
            "rating": 4.3,
            "ratingCount": 7757,
            "priceLevel": null,
            "photoUrl": "/demo/tokyo/04-ichiran-shinjuku-station-central-east-ex.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: Open 24 hours",
              "Tuesday: Open 24 hours",
              "Wednesday: Open 24 hours",
              "Thursday: Open 24 hours",
              "Friday: Open 24 hours",
              "Saturday: Open 24 hours",
              "Sunday: Open 24 hours"
            ],
            "location": {
              "lat": 35.690585899999995,
              "lng": 139.7028052
            },
            "travelToNext": "25 minute drive"
          },
          {
            "type": "activity",
            "name": "Kanda Myoujin Shrine",
            "address": "2-chōme-16-2 Sotokanda, Chiyoda City, Tokyo 101-0021, Japan",
            "location": {
              "lat": 35.702018599999995,
              "lng": 139.7678943
            },
            "description": "A Shinto shrine in Sotokanda that serves as a spiritual center for the surrounding Akihabara district and its tech culture.",
            "categoryTag": "Landmark · Sotokanda",
            "startTime": "14:55",
            "durationMinutes": 60,
            "mealType": null,
            "travelToNext": "15 minute drive",
            "photoUrl": "/demo/tokyo/05-kanda-myoujin-shrine.jpg",
            "rating": 4.4,
            "ratingCount": 26051,
            "priceLevel": null,
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: Open 24 hours",
              "Tuesday: Open 24 hours",
              "Wednesday: Open 24 hours",
              "Thursday: Open 24 hours",
              "Friday: Open 24 hours",
              "Saturday: Open 24 hours",
              "Sunday: Open 24 hours"
            ]
          },
          {
            "time": "morning",
            "type": "activity",
            "name": "Fish Market Tsukiji Outer Market",
            "categoryTag": "Wholesaler · Tsukiji",
            "description": "A sprawling outdoor seafood and produce market where Tokyo's culinary energy is on full display, perfect for a quick walk among vendors and stalls.",
            "startTime": "16:10",
            "durationMinutes": 60,
            "mealType": null,
            "address": "Japan, 〒104-0045 Tokyo, Chuo City, Tsukiji, 4-chōme−16 および６丁目一部",
            "rating": 4.2,
            "ratingCount": 56046,
            "priceLevel": null,
            "photoUrl": "/demo/tokyo/06-fish-market-tsukiji-outer-market.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.6647703,
              "lng": 139.7702515
            },
            "travelToNext": "15 minute drive"
          },
          {
            "time": "afternoon",
            "type": "activity",
            "name": "Yodobashi Akiba",
            "categoryTag": "Shop · Kanda Hanaokachō",
            "description": "A massive electronics and home goods store in Kanda that offers multiple floors of cameras, computers, appliances and entertainment products.",
            "startTime": "17:25",
            "durationMinutes": 60,
            "mealType": null,
            "address": "1-1 Kanda Hanaokachō, Chiyoda City, Tokyo 101-0028, Japan",
            "rating": 4.2,
            "ratingCount": 26647,
            "priceLevel": null,
            "photoUrl": "/demo/tokyo/07-yodobashi-akiba.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: 9:30 AM – 10:00 PM",
              "Tuesday: 9:30 AM – 10:00 PM",
              "Wednesday: 9:30 AM – 10:00 PM",
              "Thursday: 9:30 AM – 10:00 PM",
              "Friday: 9:30 AM – 10:00 PM",
              "Saturday: 9:30 AM – 10:00 PM",
              "Sunday: 9:30 AM – 10:00 PM"
            ],
            "location": {
              "lat": 35.698917,
              "lng": 139.774798
            },
            "travelToNext": "5 minute drive"
          },
          {
            "time": "afternoon",
            "type": "activity",
            "name": "Akihabara Electric Town",
            "categoryTag": "Landmark · Sotokanda",
            "description": "Tokyo's epicentre of anime, manga, and gaming culture, with towering shops devoted to figurines, video games, and pop-culture merchandise.",
            "startTime": "18:30",
            "durationMinutes": 60,
            "mealType": null,
            "address": "1 Chome-12 Sotokanda, Chiyoda City, Tokyo 101-0021, Japan",
            "rating": 4.5,
            "ratingCount": 8883,
            "priceLevel": null,
            "photoUrl": "/demo/tokyo/08-akihabara-electric-town.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.699717799999995,
              "lng": 139.7713799
            },
            "travelToNext": "30 minute drive"
          },
          {
            "time": "dinner",
            "type": "meal",
            "name": "Gonpachi Nishi-Azabu",
            "categoryTag": "Restaurant · Nishiazabu",
            "description": "A lively izakaya in Nishi-Azabu with eclectic decor and solid mid-range Japanese dishes, known as a filming location for Kill Bill.",
            "startTime": "20:00",
            "durationMinutes": 60,
            "mealType": "dinner",
            "address": "1-chōme-13-11 Nishiazabu, Minato City, Tokyo 106-0031, Japan",
            "rating": 4.3,
            "ratingCount": 8348,
            "priceLevel": null,
            "photoUrl": "/demo/tokyo/09-gonpachi-nishi-azabu.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: 11:30 AM – 3:30 AM",
              "Tuesday: 11:30 AM – 3:30 AM",
              "Wednesday: 11:30 AM – 3:30 AM",
              "Thursday: 11:30 AM – 3:30 AM",
              "Friday: 11:30 AM – 3:30 AM",
              "Saturday: 11:30 AM – 3:30 AM",
              "Sunday: 11:30 AM – 3:30 AM"
            ],
            "location": {
              "lat": 35.6601742,
              "lng": 139.7235797
            },
            "travelToNext": "15 minute drive"
          },
          {
            "time": "evening",
            "type": "activity",
            "name": "CROSS ROPPONGI",
            "categoryTag": "Nightlife · Roppongi",
            "description": "A nightclub and bar in Roppongi that draws an international crowd looking for late-night entertainment and dancing.",
            "startTime": "21:15",
            "durationMinutes": 120,
            "mealType": null,
            "address": "Japan, 〒106-0032 Tokyo, Minato City, Roppongi, 6-chōme−1−３ 六門ビル 3F",
            "rating": 4.8,
            "ratingCount": 413,
            "priceLevel": "PRICE_LEVEL_MODERATE",
            "photoUrl": "/demo/tokyo/10-cross-roppongi.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: Closed",
              "Tuesday: 8:00 PM – 5:00 AM",
              "Wednesday: 8:00 PM – 5:00 AM",
              "Thursday: 8:00 PM – 5:00 AM",
              "Friday: 8:00 PM – 5:00 AM",
              "Saturday: 8:00 PM – 5:00 AM",
              "Sunday: Closed"
            ],
            "location": {
              "lat": 35.6628024,
              "lng": 139.7322523
            },
            "travelToNext": "20 minute drive"
          },
          {
            "type": "accommodation",
            "name": "Mandarin Oriental, Tokyo",
            "categoryTag": "Hotel · Nihonbashimuromachi",
            "address": "2-chōme-1-1 Nihonbashimuromachi, Chuo City, Tokyo 103-8328, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/01-mandarin-oriental-tokyo.jpg",
            "location": {
              "lat": 35.6870475,
              "lng": 139.7730634
            },
            "hasHours": false,
            "weekdayDescriptions": null,
            "mealType": null,
            "durationMinutes": null,
            "travelToNext": null,
            "startTime": "23:35",
            "description": "Back at Mandarin Oriental, Tokyo."
          }
        ],
        "stopCount": 9,
        "pacingLevel": 1
      },
      {
        "day": 2,
        "theme": "Shrines, Architecture & Urban Exploration",
        "breakfastAtAccommodation": true,
        "breakfastTime": "09:00",
        "items": [
          {
            "type": "accommodation",
            "name": "Mandarin Oriental, Tokyo",
            "categoryTag": "Hotel · Nihonbashimuromachi",
            "address": "2-chōme-1-1 Nihonbashimuromachi, Chuo City, Tokyo 103-8328, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/01-mandarin-oriental-tokyo.jpg",
            "location": {
              "lat": 35.6870475,
              "lng": 139.7730634
            },
            "hasHours": false,
            "weekdayDescriptions": null,
            "mealType": "breakfast",
            "durationMinutes": 60,
            "travelToNext": "25 minute drive",
            "startTime": "09:00",
            "description": "Breakfast at Mandarin Oriental, Tokyo."
          },
          {
            "time": "afternoon",
            "type": "activity",
            "name": "Takeshita Street",
            "categoryTag": "Landmark · Jingūmae",
            "description": "Harajuku's iconic pedestrian shopping street crammed with fashion boutiques, cafés, and youth culture, a sensory immersion in contemporary Tokyo style.",
            "startTime": "10:25",
            "durationMinutes": 180,
            "mealType": null,
            "address": "1-chōme-16-6 Jingūmae, Shibuya, Tokyo 150-0001, Japan",
            "rating": 4.2,
            "ratingCount": 1705,
            "priceLevel": null,
            "photoUrl": "/demo/tokyo/11-takeshita-street.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: Open 24 hours",
              "Tuesday: Open 24 hours",
              "Wednesday: Open 24 hours",
              "Thursday: Open 24 hours",
              "Friday: Open 24 hours",
              "Saturday: Open 24 hours",
              "Sunday: Open 24 hours"
            ],
            "location": {
              "lat": 35.6712601,
              "lng": 139.7046761
            },
            "travelToNext": "5 minute drive"
          },
          {
            "time": "lunch",
            "type": "meal",
            "name": "AFURI Harajuku",
            "categoryTag": "Restaurant · Sendagaya",
            "description": "A ramen restaurant in Sendagaya near Harajuku known for its light yuzu-scented broth and modern take on traditional ramen.",
            "startTime": "13:30",
            "durationMinutes": 60,
            "mealType": "lunch",
            "address": "Japan, 〒151-0051 Tokyo, Shibuya, Sendagaya, 3-chōme−63−１ グランデフォレスタ原宿 1F",
            "rating": 4.5,
            "ratingCount": 6202,
            "priceLevel": "PRICE_LEVEL_MODERATE",
            "photoUrl": "/demo/tokyo/12-afuri-harajuku.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: 10:00 AM – 11:00 PM",
              "Tuesday: 10:00 AM – 11:00 PM",
              "Wednesday: 10:00 AM – 11:00 PM",
              "Thursday: 10:00 AM – 11:00 PM",
              "Friday: 10:00 AM – 11:00 PM",
              "Saturday: 10:00 AM – 11:00 PM",
              "Sunday: 10:00 AM – 11:00 PM"
            ],
            "location": {
              "lat": 35.6730053,
              "lng": 139.7038019
            },
            "travelToNext": "20 minute drive"
          },
          {
            "time": "morning",
            "type": "activity",
            "name": "Meiji Jingu",
            "categoryTag": "Landmark · Yoyogikamizonochō",
            "description": "A major Shinto shrine set within a peaceful forested area in Yoyogi, dedicated to Emperor Meiji and Empress Shoken.",
            "startTime": "14:50",
            "durationMinutes": 135,
            "mealType": null,
            "address": "1-1 Yoyogikamizonochō, Shibuya, Tokyo 151-8557, Japan",
            "rating": 4.6,
            "ratingCount": 52732,
            "priceLevel": null,
            "photoUrl": "/demo/tokyo/13-meiji-jingu.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.6763976,
              "lng": 139.6993259
            },
            "travelToNext": "25 minute drive"
          },
          {
            "time": "morning",
            "type": "activity",
            "name": "Yoyogi Park",
            "categoryTag": "Park · Yoyogikamizonochō",
            "description": "A sprawling urban green space adjacent to Meiji Shrine, perfect for a short walk and breathing room among Tokyo's densest neighbourhoods.",
            "startTime": "17:30",
            "durationMinutes": 135,
            "mealType": null,
            "address": "2-1 Yoyogikamizonochō, Shibuya, Tokyo 151-0052, Japan",
            "rating": 4.4,
            "ratingCount": 27504,
            "priceLevel": null,
            "photoUrl": "/demo/tokyo/14-yoyogi-park.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: Open 24 hours",
              "Tuesday: Open 24 hours",
              "Wednesday: Open 24 hours",
              "Thursday: Open 24 hours",
              "Friday: Open 24 hours",
              "Saturday: Open 24 hours",
              "Sunday: Open 24 hours"
            ],
            "location": {
              "lat": 35.6700649,
              "lng": 139.6949656
            },
            "travelToNext": "15 minute drive"
          },
          {
            "time": "dinner",
            "type": "meal",
            "name": "MO-MO-PARADISE Shibuya Center-gai",
            "categoryTag": "Restaurant · Udagawachō",
            "description": "A hot pot restaurant in Shibuya's Center-gai where diners cook their own shabu-shabu or sukiyaki at the table with all-you-can-eat options.",
            "startTime": "20:00",
            "durationMinutes": 60,
            "mealType": "dinner",
            "address": "Japan, 〒150-0042 Tokyo, Shibuya, Udagawachō, 31−2 渋谷 6F",
            "rating": 4.9,
            "ratingCount": 10005,
            "priceLevel": "PRICE_LEVEL_MODERATE",
            "photoUrl": "/demo/tokyo/15-mo-mo-paradise-shibuya-center-gai.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: 11:30 AM – 3:00 PM, 5:00 – 10:30 PM",
              "Tuesday: 11:30 AM – 3:00 PM, 5:00 – 10:30 PM",
              "Wednesday: 11:30 AM – 3:00 PM, 5:00 – 10:30 PM",
              "Thursday: 11:30 AM – 3:00 PM, 5:00 – 10:30 PM",
              "Friday: 11:30 AM – 3:00 PM, 5:00 – 10:30 PM",
              "Saturday: 11:30 AM – 3:00 PM, 5:00 – 10:30 PM",
              "Sunday: 11:30 AM – 3:00 PM, 5:00 – 10:30 PM"
            ],
            "location": {
              "lat": 35.6613618,
              "lng": 139.6976195
            },
            "travelToNext": "25 minute drive"
          },
          {
            "type": "accommodation",
            "name": "Mandarin Oriental, Tokyo",
            "categoryTag": "Hotel · Nihonbashimuromachi",
            "address": "2-chōme-1-1 Nihonbashimuromachi, Chuo City, Tokyo 103-8328, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/01-mandarin-oriental-tokyo.jpg",
            "location": {
              "lat": 35.6870475,
              "lng": 139.7730634
            },
            "hasHours": false,
            "weekdayDescriptions": null,
            "mealType": null,
            "durationMinutes": null,
            "travelToNext": null,
            "startTime": "21:25",
            "description": "Back at Mandarin Oriental, Tokyo."
          }
        ],
        "stopCount": 7,
        "pacingLevel": 0.88
      }
    ],
    "pacingLabel": "Busy"
  },
  "slow": {
    "label": "Slow & Immersive",
    "tagline": "Fewer stops, deeper dives, unhurried Tokyo.",
    "divergenceLabel": "This itinerary trades breadth for depth, lingering at each neighbourhood and activity rather than rushing between landmarks, with full meals and evening venues built into a realistic pace.",
    "days": [
      {
        "day": 1,
        "theme": "Sacred Temples & Modern Towers",
        "breakfastAtAccommodation": true,
        "breakfastTime": "09:00",
        "items": [
          {
            "type": "accommodation",
            "name": "Mandarin Oriental, Tokyo",
            "categoryTag": "Hotel · Nihonbashimuromachi",
            "address": "2-chōme-1-1 Nihonbashimuromachi, Chuo City, Tokyo 103-8328, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/01-mandarin-oriental-tokyo.jpg",
            "location": {
              "lat": 35.6870475,
              "lng": 139.7730634
            },
            "hasHours": false,
            "weekdayDescriptions": null,
            "mealType": "breakfast",
            "durationMinutes": 120,
            "travelToNext": "25 minute drive",
            "startTime": "09:00",
            "description": "Breakfast at Mandarin Oriental, Tokyo."
          },
          {
            "time": "afternoon",
            "type": "activity",
            "name": "Tokyo Skytree",
            "categoryTag": "Landmark · Oshiage",
            "description": "A soaring modern architectural icon offering panoramic city views from 350 metres; represents Tokyo's contemporary skyline in sharp contrast to Asakusa's tradition.",
            "startTime": "11:25",
            "durationMinutes": 90,
            "mealType": null,
            "address": "1-chōme-1-2 Oshiage, Sumida City, Tokyo 131-0045, Japan",
            "rating": 4.4,
            "ratingCount": 119180,
            "priceLevel": null,
            "photoUrl": "/demo/tokyo/16-tokyo-skytree.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: 10:00 AM – 10:00 PM",
              "Tuesday: 10:00 AM – 10:00 PM",
              "Wednesday: 10:00 AM – 10:00 PM",
              "Thursday: 10:00 AM – 10:00 PM",
              "Friday: 10:00 AM – 10:00 PM",
              "Saturday: 9:00 AM – 10:00 PM",
              "Sunday: 9:00 AM – 10:00 PM"
            ],
            "location": {
              "lat": 35.7100627,
              "lng": 139.81070040000003
            },
            "travelToNext": "35 minute drive"
          },
          {
            "time": "lunch",
            "type": "meal",
            "name": "ICHIRAN Shinjuku Station Central East Exit",
            "categoryTag": "Restaurant · Shinjuku",
            "description": "A popular ramen restaurant chain known for its individual booth seating system, serving tonkotsu ramen in a focused, distraction-free dining environment.",
            "startTime": "13:30",
            "durationMinutes": 120,
            "mealType": "lunch",
            "address": "Japan, 〒160-0022 Tokyo, Shinjuku City, Shinjuku, 3-chōme−34−１１ Peace Bldg., B1F",
            "rating": 4.3,
            "ratingCount": 7757,
            "priceLevel": null,
            "photoUrl": "/demo/tokyo/04-ichiran-shinjuku-station-central-east-ex.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: Open 24 hours",
              "Tuesday: Open 24 hours",
              "Wednesday: Open 24 hours",
              "Thursday: Open 24 hours",
              "Friday: Open 24 hours",
              "Saturday: Open 24 hours",
              "Sunday: Open 24 hours"
            ],
            "location": {
              "lat": 35.690585899999995,
              "lng": 139.7028052
            },
            "travelToNext": "10 minute drive"
          },
          {
            "time": "evening",
            "type": "activity",
            "name": "T2 SHINJUKU (Nightclub)",
            "categoryTag": "Nightlife · Nishishinjuku",
            "description": "A nightclub in the Shinjuku area offering late-night entertainment with music and dancing.",
            "startTime": "15:40",
            "durationMinutes": 120,
            "mealType": null,
            "address": "Japan, 〒160-0023 Tokyo, Shinjuku City, Nishishinjuku, 7-chōme−1−１ 新宿カレイドビル 7F",
            "rating": 4.8,
            "ratingCount": 7182,
            "photoUrl": "/demo/tokyo/17-t2-shinjuku-nightclub.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: 10:00 PM – 4:30 AM",
              "Tuesday: 10:00 PM – 4:30 AM",
              "Wednesday: 10:00 PM – 4:30 AM",
              "Thursday: 10:00 PM – 4:30 AM",
              "Friday: 10:00 PM – 4:30 AM",
              "Saturday: 10:00 PM – 4:30 AM",
              "Sunday: 10:00 PM – 4:30 AM"
            ],
            "location": {
              "lat": 35.6941128,
              "lng": 139.69908709999999
            },
            "priceLevel": "PRICE_LEVEL_MODERATE",
            "travelToNext": "25 minute drive"
          },
          {
            "time": "afternoon",
            "type": "activity",
            "name": "Roppongi Hills",
            "categoryTag": "Architecture · Modern",
            "description": "A mixed-use complex in Roppongi showcasing cutting-edge urban design, with galleries, shops and public spaces; a landmark of Tokyo's modern redevelopment.",
            "startTime": "18:05",
            "durationMinutes": 105,
            "mealType": null,
            "address": "6-chōme-10-1 Roppongi, Minato City, Tokyo 106-6108, Japan",
            "rating": 4.2,
            "ratingCount": 39996,
            "priceLevel": null,
            "photoUrl": "/demo/tokyo/18-roppongi-hills.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.6607397,
              "lng": 139.7292319
            },
            "travelToNext": "10 minute drive"
          },
          {
            "time": "dinner",
            "type": "meal",
            "name": "Afuri Roppongi Hills",
            "categoryTag": "Restaurant · Roppongi",
            "description": "A ramen restaurant in Roppongi Hills known for its yuzu-infused citrus broth and lighter, modern approach to traditional ramen.",
            "startTime": "20:00",
            "durationMinutes": 120,
            "mealType": "dinner",
            "address": "Japan, 〒106-0032 Tokyo, Minato City, Roppongi, 6-chōme−4−１ ヒルズメトロハット/ハリウッドプラザ B2F",
            "rating": 4.7,
            "ratingCount": 3999,
            "priceLevel": "PRICE_LEVEL_MODERATE",
            "photoUrl": "/demo/tokyo/19-afuri-roppongi-hills.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: 11:00 AM – 11:00 PM",
              "Tuesday: 11:00 AM – 11:00 PM",
              "Wednesday: 11:00 AM – 11:00 PM",
              "Thursday: 11:00 AM – 11:00 PM",
              "Friday: 11:00 AM – 11:00 PM",
              "Saturday: 11:00 AM – 11:00 PM",
              "Sunday: 11:00 AM – 11:00 PM"
            ],
            "location": {
              "lat": 35.6614918,
              "lng": 139.7296867
            },
            "travelToNext": "15 minute drive",
            "placeId": "ChIJP1lEhXeLGGARhk5zBfKyb_A"
          },
          {
            "type": "activity",
            "name": "Yasukuni Shrine",
            "address": "3-chōme-1-1 Kudankita, Chiyoda City, Tokyo 102-0073, Japan",
            "location": {
              "lat": 35.694136,
              "lng": 139.74384899999998
            },
            "description": "A controversial Shinto shrine that commemorates Japan's war dead, including convicted war criminals, drawing both visitors and protesters.",
            "categoryTag": "Landmark · Kudankita",
            "startTime": "22:15",
            "durationMinutes": 60,
            "mealType": null,
            "travelToNext": "10 minute drive",
            "photoUrl": "/demo/tokyo/20-yasukuni-shrine.jpg",
            "rating": 4.4,
            "ratingCount": 20742,
            "priceLevel": null,
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: 6:00 AM – 6:00 PM",
              "Tuesday: 6:00 AM – 6:00 PM",
              "Wednesday: 6:00 AM – 6:00 PM",
              "Thursday: 6:00 AM – 6:00 PM",
              "Friday: 6:00 AM – 6:00 PM",
              "Saturday: 6:00 AM – 6:00 PM",
              "Sunday: 6:00 AM – 6:00 PM"
            ]
          },
          {
            "type": "activity",
            "name": "Kanda Myoujin Shrine",
            "address": "2-chōme-16-2 Sotokanda, Chiyoda City, Tokyo 101-0021, Japan",
            "location": {
              "lat": 35.702018599999995,
              "lng": 139.7678943
            },
            "description": "An ancient Shinto shrine in Akihabara area that serves as a guardian deity for Tokyo and is popular with tech enthusiasts seeking blessings.",
            "categoryTag": "Landmark · Sotokanda",
            "startTime": "23:25",
            "durationMinutes": 90,
            "mealType": null,
            "travelToNext": "10 minute drive",
            "photoUrl": "/demo/tokyo/21-kanda-myoujin-shrine.jpg",
            "rating": 4.4,
            "ratingCount": 26051,
            "priceLevel": null,
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: Open 24 hours",
              "Tuesday: Open 24 hours",
              "Wednesday: Open 24 hours",
              "Thursday: Open 24 hours",
              "Friday: Open 24 hours",
              "Saturday: Open 24 hours",
              "Sunday: Open 24 hours"
            ]
          },
          {
            "type": "accommodation",
            "name": "Mandarin Oriental, Tokyo",
            "categoryTag": "Hotel · Nihonbashimuromachi",
            "address": "2-chōme-1-1 Nihonbashimuromachi, Chuo City, Tokyo 103-8328, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/01-mandarin-oriental-tokyo.jpg",
            "location": {
              "lat": 35.6870475,
              "lng": 139.7730634
            },
            "hasHours": false,
            "weekdayDescriptions": null,
            "mealType": null,
            "durationMinutes": null,
            "travelToNext": null,
            "startTime": "01:05",
            "description": "Back at Mandarin Oriental, Tokyo."
          }
        ],
        "stopCount": 7,
        "pacingLevel": 0.88
      },
      {
        "day": 2,
        "theme": "Anime Culture & Pop Energy",
        "breakfastAtAccommodation": false,
        "items": [
          {
            "type": "accommodation",
            "name": "Mandarin Oriental, Tokyo",
            "categoryTag": "Hotel · Nihonbashimuromachi",
            "address": "2-chōme-1-1 Nihonbashimuromachi, Chuo City, Tokyo 103-8328, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/01-mandarin-oriental-tokyo.jpg",
            "location": {
              "lat": 35.6870475,
              "lng": 139.7730634
            },
            "hasHours": false,
            "weekdayDescriptions": null,
            "mealType": null,
            "durationMinutes": null,
            "travelToNext": "10 minute drive",
            "startTime": "08:50",
            "description": "Leave Mandarin Oriental, Tokyo for breakfast."
          },
          {
            "time": "breakfast",
            "type": "meal",
            "name": "Fish Market Tsukiji Outer Market",
            "categoryTag": "Wholesaler · Tsukiji",
            "description": "Tokyo's famous seafood and fresh produce market with a breakfast and early-lunch counter culture; tamagoyaki and sushi-style breakfasts at standing counters.",
            "startTime": "09:00",
            "durationMinutes": 120,
            "mealType": "breakfast",
            "address": "Japan, 〒104-0045 Tokyo, Chuo City, Tsukiji, 4-chōme−16 および６丁目一部",
            "rating": 4.2,
            "ratingCount": 56046,
            "priceLevel": null,
            "photoUrl": "/demo/tokyo/22-fish-market-tsukiji-outer-market.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.6647703,
              "lng": 139.7702515
            },
            "travelToNext": "15 minute drive"
          },
          {
            "time": "morning",
            "type": "activity",
            "name": "teamLab Borderless: MORI Building DIGITAL ART MUSEUM",
            "categoryTag": "Museum · Toranomon",
            "description": "An immersive digital art museum in Odaiba with boundary-dissolving installations; a contemporary pop-culture and technology landmark beloved in Tokyo.",
            "startTime": "11:15",
            "durationMinutes": 120,
            "mealType": null,
            "address": "Japan, 〒106-0041 Tokyo, Minato City, Toranomon, 5-chōme−9−９ Azabudai Hills Garden Plaza B, B1",
            "rating": 4.6,
            "ratingCount": 29830,
            "priceLevel": null,
            "photoUrl": "/demo/tokyo/23-teamlab-borderless-mori-building-digital.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: 8:30 AM – 9:00 PM",
              "Tuesday: 8:30 AM – 9:00 PM",
              "Wednesday: 8:30 AM – 9:00 PM",
              "Thursday: 8:30 AM – 9:00 PM",
              "Friday: 8:30 AM – 9:00 PM",
              "Saturday: 8:30 AM – 9:00 PM",
              "Sunday: 8:30 AM – 9:00 PM"
            ],
            "location": {
              "lat": 35.6620689,
              "lng": 139.7432671
            },
            "travelToNext": "15 minute drive"
          },
          {
            "time": "lunch",
            "type": "meal",
            "name": "Gonpachi Nishi-Azabu",
            "categoryTag": "Restaurant · Nishiazabu",
            "description": "A mid-range Japanese izakaya near Shibuya with yakitori, sashimi and creative small plates; casual atmosphere suited to pairs without reservation required.",
            "startTime": "13:30",
            "durationMinutes": 120,
            "mealType": "lunch",
            "address": "1-chōme-13-11 Nishiazabu, Minato City, Tokyo 106-0031, Japan",
            "rating": 4.3,
            "ratingCount": 8348,
            "priceLevel": null,
            "photoUrl": "/demo/tokyo/09-gonpachi-nishi-azabu.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: 11:30 AM – 3:30 AM",
              "Tuesday: 11:30 AM – 3:30 AM",
              "Wednesday: 11:30 AM – 3:30 AM",
              "Thursday: 11:30 AM – 3:30 AM",
              "Friday: 11:30 AM – 3:30 AM",
              "Saturday: 11:30 AM – 3:30 AM",
              "Sunday: 11:30 AM – 3:30 AM"
            ],
            "location": {
              "lat": 35.6601742,
              "lng": 139.7235797
            },
            "travelToNext": "15 minute drive"
          },
          {
            "time": "afternoon",
            "type": "activity",
            "name": "Meiji Jingu",
            "categoryTag": "Landmark · Yoyogikamizonochō",
            "description": "Tokyo's most prominent Shinto shrine, set within a vast forested park, dedicated to Emperor Meiji and Empress Shoken.",
            "startTime": "15:45",
            "durationMinutes": 105,
            "mealType": null,
            "address": "1-1 Yoyogikamizonochō, Shibuya, Tokyo 151-8557, Japan",
            "rating": 4.6,
            "ratingCount": 52732,
            "priceLevel": null,
            "photoUrl": "/demo/tokyo/13-meiji-jingu.jpg",
            "hasHours": false,
            "weekdayDescriptions": null,
            "location": {
              "lat": 35.6763976,
              "lng": 139.6993259
            },
            "travelToNext": "25 minute drive"
          },
          {
            "type": "activity",
            "name": "Tokyo Daijingu",
            "address": "2-chōme-4-1 Fujimi, Chiyoda City, Tokyo 102-0071, Japan",
            "location": {
              "lat": 35.6999858,
              "lng": 139.746891
            },
            "description": "A Shinto shrine known for its association with marriage and matchmaking, drawing couples and those seeking romantic fortune.",
            "categoryTag": "Landmark · Fujimi",
            "startTime": "17:55",
            "durationMinutes": 105,
            "mealType": null,
            "travelToNext": "20 minute drive",
            "photoUrl": "/demo/tokyo/24-tokyo-daijingu.jpg",
            "rating": 4.4,
            "ratingCount": 12473,
            "priceLevel": null,
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: 6:00 AM – 9:00 PM",
              "Tuesday: 6:00 AM – 9:00 PM",
              "Wednesday: 6:00 AM – 9:00 PM",
              "Thursday: 6:00 AM – 9:00 PM",
              "Friday: 6:00 AM – 9:00 PM",
              "Saturday: 6:00 AM – 9:00 PM",
              "Sunday: 6:00 AM – 9:00 PM"
            ]
          },
          {
            "time": "dinner",
            "type": "meal",
            "name": "Tempura Shinjuku Tsunahachi Ginza",
            "categoryTag": "Restaurant · Ginza",
            "description": "A tempura restaurant in Ginza serving battered and deep-fried seafood and vegetables in the traditional Japanese style.",
            "startTime": "20:00",
            "durationMinutes": 120,
            "mealType": "dinner",
            "address": "Japan, 〒104-0061 Tokyo, Chuo City, Ginza, 3-chōme−6−１ 松屋銀座 8F",
            "rating": 4.1,
            "ratingCount": 436,
            "priceLevel": "PRICE_LEVEL_MODERATE",
            "photoUrl": "/demo/tokyo/25-tempura-shinjuku-tsunahachi-ginza.jpg",
            "hasHours": true,
            "weekdayDescriptions": [
              "Monday: 11:00 AM – 10:00 PM",
              "Tuesday: 11:00 AM – 10:00 PM",
              "Wednesday: 11:00 AM – 10:00 PM",
              "Thursday: 11:00 AM – 10:00 PM",
              "Friday: 11:00 AM – 10:00 PM",
              "Saturday: 11:00 AM – 10:00 PM",
              "Sunday: 11:00 AM – 9:30 PM"
            ],
            "location": {
              "lat": 35.671938499999996,
              "lng": 139.7662641
            },
            "travelToNext": "10 minute drive"
          },
          {
            "type": "accommodation",
            "name": "Mandarin Oriental, Tokyo",
            "categoryTag": "Hotel · Nihonbashimuromachi",
            "address": "2-chōme-1-1 Nihonbashimuromachi, Chuo City, Tokyo 103-8328, Japan",
            "rating": null,
            "ratingCount": null,
            "photoUrl": "/demo/tokyo/01-mandarin-oriental-tokyo.jpg",
            "location": {
              "lat": 35.6870475,
              "lng": 139.7730634
            },
            "hasHours": false,
            "weekdayDescriptions": null,
            "mealType": null,
            "durationMinutes": null,
            "travelToNext": null,
            "startTime": "22:10",
            "description": "Back at Mandarin Oriental, Tokyo."
          }
        ],
        "stopCount": 6,
        "pacingLevel": 0.75
      }
    ],
    "pacingLabel": "Relaxed"
  }
}

// The accommodation the demo was generated against. demoTrips.js imports this
// rather than keeping its own copy, so the card, the Finalise screen and the
// itinerary's bookend stops can never disagree about which hotel this is.
export const TOKYO_ACCOMMODATION = {
  "placeId": "ChIJ281VfFWJGGARYaR_hmZuo0I",
  "name": "Mandarin Oriental, Tokyo",
  "categoryTag": "Hotel · Nihonbashimuromachi",
  "address": "2-chōme-1-1 Nihonbashimuromachi, Chuo City, Tokyo 103-8328, Japan",
  "priceLevelLabel": null,
  "photoUrl": "/demo/tokyo/01-mandarin-oriental-tokyo.jpg",
  "location": {
    "lat": 35.6870475,
    "lng": 139.7730634
  },
  "budget": "Luxury",
  "nights": 2,
  "priceRange": {
    "min": 120000,
    "max": 250000,
    "currencyCode": "JPY",
    "estimated": true
  },
  "destinationCurrency": "JPY"
}
